# Generated by Django 2.1.dev20180423170307 on 2018-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI_CUIT', models.CharField(max_length=14)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Localidad', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=30)),
                ('TipoDeCliente', models.CharField(max_length=7)),
                ('DescuentoServicio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('DescuentoProducto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('CuentaCorriente', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
