# Generated by Django 2.1.1 on 2018-09-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeInsumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Consulta'), ('Q', 'Quirurgica')], default='Q', max_length=1)),
                ('nombre', models.CharField(help_text='Ingresa el nombre del Servicio', max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tiempoEstimado', models.PositiveSmallIntegerField(help_text='Tiempo en minutos de Duración del Servicio')),
                ('precioManoDeObra', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeInsumos.Insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeServicios.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(through='GestionDeServicios.ServicioInsumo', to='GestionDeInsumos.Insumo'),
        ),
    ]
