# Generated by Django 2.0.8 on 2018-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, error_messages={'max_length': 'La descripcion puede tener a lo sumo 200 caracteres'}, help_text='Ingrese la descripcion del Servicio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El nombre de servicio es obligarotio', 'max_length': 'El nombre puede tener a lo sumo 50 caracteres'}, help_text='Ingrese el nombre del Servicio', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tiempoEstimado',
            field=models.PositiveSmallIntegerField(error_messages={'blank': 'El tiempo estimado del servicio es obligarotio'}, help_text='Tiempo en minutos de Duración del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('C', 'Consulta'), ('Q', 'Quirurgica')], default='Q', error_messages={'blank': 'El tipo de servicio es obligarotio'}, help_text='Tipo de Servicio (Consulta-Cirugia)', max_length=1),
        ),
    ]
