# Generated by Django 2.0.8 on 2018-10-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeServicios', '0003_auto_20181014_2054'),
        ('GestionDeServicios', '0003_auto_20181015_1159'),
    ]

    operations = [
    ]
