# Generated by Django 2.0.8 on 2018-10-24 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre es obligatorio', 'max_length': 'El nombre puede tener a lo sumo 50 caracteres', 'unique': 'Otro insumo tiene ese nombre'}, help_text='Nombre del Insumo', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z-_ .]{3,100}$')])),
                ('formaDePresentacion', models.PositiveSmallIntegerField(choices=[(1, 'g'), (2, 'cm3'), (3, 'unidad'), (4, 'kg'), (5, 'litro'), (6, 'docena')], error_messages={'blank': 'La unidad de medida es obligatoria', 'invalid_choice': 'Opcion invalida'}, help_text='Forma de Presentacion del Insumo')),
                ('precioPorUnidad', models.DecimalField(decimal_places=2, help_text='Precio del Insumo', max_digits=7)),
                ('precioDeCompra', models.DecimalField(decimal_places=2, help_text='Precio del Insumo', max_digits=7)),
                ('rubro', models.CharField(help_text='Nombre del rubro al que pertenece', max_length=50)),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
    ]
