# Generated by Django 2.1.1 on 2018-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('formaDePresentacion', models.PositiveSmallIntegerField(choices=[(1, 'g'), (2, 'cm3'), (3, 'unidad'), (4, 'kg'), (5, 'litro'), (6, 'docena')])),
                ('precioPorUnidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rubro', models.CharField(max_length=50)),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
    ]
