# Generated by Django 2.0.8 on 2018-10-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeInsumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='baja',
            field=models.BooleanField(default=False, help_text='Deshabilitado'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
