# Generated by Django 2.0.8 on 2018-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeInsumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='rubro',
            field=models.CharField(help_text='Nombre del rubro al que pertenece', max_length=50),
        ),
    ]
