# Generated by Django 2.0.8 on 2018-10-11 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                #('patente', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateTimeField()),
                ('especie', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeClientes.Cliente')),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
    ]
