# Generated by Django 2.0.8 on 2018-10-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fechaNacimiento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(error_messages={}, help_text='ingrese cliente', on_delete=django.db.models.deletion.CASCADE, to='GestionDeClientes.Cliente'),
        ),
    ]
