# Generated by Django 2.0.8 on 2018-10-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeMascotas', '0002_auto_20181009_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(error_messages={}, on_delete=django.db.models.deletion.CASCADE, to='GestionDeClientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='patente',
            field=models.CharField(error_messages={'blank': 'la patente es obligatoria', 'max_length': 'la patente puede tener a lo sumo 6 caracteres', 'unique': 'Otra mascota tiene esa patente'}, help_text='patente la mascota', max_length=6, unique=True),
        ),
    ]
