# Generated by Django 2.0.8 on 2018-11-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeFacturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, error_messages={'blank': 'La fecha es obligatoria'}, help_text='Fecha de pago')),
                ('importeTotal', models.IntegerField(error_messages={'blank': 'El importe es obligatorio'})),
                ('baja', models.BooleanField(default=False)),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDeFacturas.Factura')),
            ],
        ),
    ]
