# Generated by Django 2.0.8 on 2019-12-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeFacturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, error_messages={'blank': 'La fecha es obligatoria'}, help_text='Fecha de pago')),
                ('importeTotal', models.IntegerField(error_messages={'blank': 'El importe es obligatorio'})),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDeFacturas.Factura')),
            ],
            options={
                'ordering': ['fecha'],
                'permissions': (('pago_crear', 'pago_crear'), ('pago_ver', 'pago_ver'), ('pago_listar', 'pago_listar')),
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pago',
            unique_together={('id', 'factura')},
        ),
    ]
