# Generated by Django 2.1.dev20180423170307 on 2018-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(error_messages={'blank': 'La fecha es obligatoria'}, help_text='Fecha de pago')),
                ('importeTotal', models.IntegerField(error_messages={'blank': 'El importe es obligatorio'})),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
    ]
