# Generated by Django 2.0.8 on 2018-11-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeFacturas', '0003_remove_factura_pago'),
        ('GestionDePagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDeFacturas.Factura'),
        ),
    ]
