# Generated by Django 2.0.8 on 2018-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDePagos', '0002_pago_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now=True, error_messages={'blank': 'La fecha es obligatoria'}, help_text='Fecha de pago'),
        ),
    ]
