# Generated by Django 2.0.8 on 2018-11-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDePracticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practica',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='recargo',
        ),
    ]
