# Generated by Django 2.0.8 on 2018-11-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDePracticas', '0002_auto_20181112_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='turno',
            field=models.DateTimeField(null=True),
        ),
    ]
