# Generated by Django 2.0.8 on 2018-11-12 12:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioDeCompra',
            field=models.DecimalField(decimal_places=2, help_text='Precio de Compra del Producto', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El precio no debe ser menor a $0.00'), django.core.validators.MaxValueValidator(Decimal('9000'), message='El precio no puede ser mayor a $9000.00')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioPorUnidad',
            field=models.DecimalField(decimal_places=2, help_text='Precio del Producto', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El precio no debe ser menor a $0.00'), django.core.validators.MaxValueValidator(Decimal('9000'), message='El precio no puede ser mayor a $9000.00')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(error_messages={'blank': 'El rubro es obligatorio'}, help_text='Nombre del rubro', on_delete=django.db.models.deletion.CASCADE, to='GestionDeRubros.Rubro'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(help_text='Stock del Producto', validators=[django.core.validators.MinValueValidator(1, message='El Stock debe ser mayor a 0'), django.core.validators.MaxValueValidator(99, message='El Stock no puede ser mayor a 99')]),
        ),
    ]
