# Generated by Django 2.0.8 on 2018-10-27 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeProductos', '0003_auto_20181026_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, error_messages={'max_length': 'La descripcion puede tener a lo sumo 150 caracteres'}, help_text='Descripcion del Rubro', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=1, error_messages={'blank': 'La marca es obligatoria', 'max_length': 'La marca puede tener a lo sumo 50 caracteres'}, help_text='Marca del Producto', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z-_ .]{3,100}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, help_text='Stock del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El nombre es obligatorio', 'max_length': 'El nombre puede tener a lo sumo 50 caracteres'}, help_text='Nombre del Producto', max_length=50, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z-_ .]{3,100}$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(error_messages={'blank': 'El rubro es obligatorio'}, help_text='Nombre del rubro al que pertenece', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='GestionDeRubros.Rubro'),
        ),
    ]
