# Generated by Django 2.0.8 on 2018-09-28 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAtencion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre es obligatorio', 'max_length': 'El nombre puede tener a lo sumo 100 caracteres', 'unique': 'Otro tipo de atencion tiene ese nombre'}, help_text='Nombre del tipo de atencion', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z-_ .]{3,100}$')])),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion del tipo de atencion')),
                ('emergencia', models.BooleanField(default=False, help_text='Determina el grado de urgencia del tipo de atencion')),
                ('lugar', models.CharField(choices=[('VET', 'Veterinaria'), ('DOM', 'Domicilio')], default='VET', error_messages={'blank': 'El lugar de atencion es obligatorio', 'invalid_choice': 'Opcion invalida'}, help_text='Lugar en donde se realiza el tipo de atencion', max_length=3, verbose_name='Lugar de atencion')),
                ('recargo', models.FloatField(default=0, error_messages={'blank': 'El porcentaje de recargo es obligatorio'}, help_text='Porcentaje de recargo sobre el costo del servicio a aplicar', validators=[django.core.validators.MinValueValidator(0, message='ERROR'), django.core.validators.MaxValueValidator(100, message='ERRORR')], verbose_name='Porcentaje de recargo')),
                ('tipo_de_servicio', models.CharField(choices=[('C', 'Consulta'), ('Q', 'Quirurgica')], error_messages={'blank': 'El tipo de servicio es obligatorio', 'invalid_choice': 'Opcion invalida'}, help_text='Tipo de servicio', max_length=25, verbose_name='Tipo de servicio')),
                ('inicio_franja_horaria', models.TimeField(error_messages={'blank': 'El inicio de horario de atencion es obligatorio', 'invalid': 'El formato debe ser HH:MM, por ejemplo "01:23"'}, help_text='Hora de inicio del tipo de atencion', verbose_name='Inicio de horario de atencion')),
                ('fin_franja_horaria', models.TimeField(error_messages={'blank': 'El inicio de horario de atencion es obligatorio', 'invalid': 'El formato debe ser HH:MM, por ejemplo "01:23"'}, help_text='Hora de finalizacion del tipo de atencion', verbose_name='Fin de horario de atencion')),
                ('baja', models.BooleanField(default=False, help_text='Deshabilitado')),
            ],
        ),
    ]
