# Generated by Django 2.1.dev20180423170307 on 2019-12-17 14:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAtencion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre es obligatorio', 'max_length': 'El nombre puede tener a lo sumo 100 caracteres', 'unique': 'Otro tipo de atencion tiene ese nombre'}, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9áéíóúÁÉÍÓÚñÑa-zA-Z-_ .]{1,100}$')])),
                ('descripcion', models.TextField(blank=True)),
                ('emergencia', models.BooleanField(default=False)),
                ('lugar', models.CharField(choices=[('V', 'Veterinaria'), ('D', 'Domicilio')], default='V', error_messages={'blank': 'El lugar de atencion es obligatorio', 'invalid_choice': 'La opcion no es valida'}, max_length=1)),
                ('recargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El recargo no puede ser menor a 0.00'), django.core.validators.MaxValueValidator(Decimal('900'), message='El recargo no puede ser mayor a 900.00'), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('tipoDeServicio', models.CharField(choices=[('C', 'Consulta'), ('Q', 'Cirugia')], error_messages={'blank': 'El tipo de servicio es obligatorio', 'invalid_choice': 'La opcion no es valida'}, max_length=1)),
                ('inicioFranjaHoraria', models.TimeField(error_messages={'blank': 'El inicio de horario de atencion es obligatorio', 'invalid': 'El formato debe ser <horas>:<minutos>, por ejemplo 01:23'})),
                ('finFranjaHoraria', models.TimeField(error_messages={'blank': 'El inicio de horario de atencion es obligatorio', 'invalid': 'El formato debe ser <horas>:<minutos>, por ejemplo 01:23'})),
                ('baja', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('tipodeatencion_crear', 'crear'), ('tipodeatencion_modificar', 'modificar'), ('tipodeatencion_eliminar', 'eliminar'), ('tipodeatencion_ver_habilitados', 'ver_habilitados'), ('tipodeatencion_listar_habilitados', 'listar_habilitados'), ('tipodeatencion_ver_no_habilitados', 'ver_no_habilitados'), ('tipodeatencion_listar_no_habilitados', 'listar_no_habilitados'), ('tipodeatencion_exportar_excel_habilitados', 'exportar_habilitados_excel'), ('tipodeatencion_exportar_excel_deshabilitados', 'exportar_deshabilitados_excel')),
                'default_permissions': (),
            },
        ),
    ]
