# Generated by Django 2.0.9 on 2018-11-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeTiposDeAtencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeatencion',
            name='lugar',
            field=models.CharField(choices=[('DOM', 'Domicilio'), ('VET', 'Veterinaria')], default='VET', error_messages={'blank': 'El lugar de atencion es obligatorio', 'invalid_choice': 'Opcion invalida'}, max_length=3),
        ),
    ]
