# Generated by Django 2.0.8 on 2018-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeTiposDeAtencion', '0002_auto_20181025_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeatencion',
            name='lugar',
            field=models.CharField(choices=[('VET', 'Veterinaria'), ('DOM', 'Domicilio')], default='VET', error_messages={'blank': 'El lugar de atencion es obligatorio', 'invalid_choice': 'Opcion invalida'}, max_length=3),
        ),
    ]
