# Generated by Django 2.1.1 on 2018-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('formaDePresentacion', models.CharField(max_length=50)),
                ('precioPorUnidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rubro', models.CharField(max_length=50)),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
    ]
