# Generated by Django 2.1.dev20180423170307 on 2019-12-16 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre es obligatorio', 'max_length': 'El nombre puede tener a lo sumo 50 caracteres'}, help_text='Nombre del Rubro', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z-_ .]{3,100}$')])),
                ('descripcion', models.TextField(blank=True, error_messages={'max_length': 'La descripcion puede tener a lo sumo 50 caracteres'}, help_text='Descripcion del Rubro', max_length=150, null=True)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre', 'descripcion'],
                'permissions': (('rubro_crear', 'crear'), ('rubro_modificar', 'modificar'), ('rubro_eliminar', 'eliminar'), ('rubro_ver_habilitados', 'ver_habilitados'), ('rubro_listar_habilitados', 'listar_habilitados'), ('rubro_ver_no_habilitados', 'ver_no_habilitados'), ('rubro_listar_no_habilitados', 'listar_no_habilitados'), ('deshabilitar_rubro', 'deshabilitar_rubro')),
                'default_permissions': (),
            },
        ),
    ]
