# Generated by Django 2.0.8 on 2018-10-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeRubros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='descripcion',
            field=models.TextField(blank=True, error_messages={'max_length': 'La descripcion puede tener a lo sumo 50 caracteres'}, help_text='Descripcion del Rubro', max_length=150, null=True),
        ),
    ]
