# Generated by Django 2.1.1 on 2018-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI_CUIT', models.CharField(max_length=14)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('tipoDeCliente', models.CharField(choices=[('E', 'Especial'), ('C', 'Comun')], default='C', max_length=1)),
                ('descuentoServicio', models.PositiveSmallIntegerField()),
                ('descuentoProducto', models.PositiveSmallIntegerField()),
                ('cuentaCorriente', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
