# Generated by Django 2.0.8 on 2018-10-12 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, error_messages={'max_length': 'El celular puede tener a lo sumo 12 caracteres', 'unique': 'Otro cliente tiene ese celular'}, help_text='Celular del Cliente sin el 0', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{1,12}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, error_messages={'max_length': 'El telefono puede tener a lo sumo 7 caracteres'}, help_text='Telefono del Cliente', max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{1,12}$')]),
        ),
    ]
