<<<<<<< HEAD
# Generated by Django 2.0.8 on 2018-09-28 20:26
>>>>>>> f828e738db5ea61f7220d386d5bc9188c0c498be

from django.db import migrations, models


<<<<<<< HEAD
=======

>>>>>>> f828e738db5ea61f7220d386d5bc9188c0c498be
class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
<<<<<<< HEAD
            field=models.CharField(default=15678907, max_length=10),
        
>>>>>>> f828e738db5ea61f7220d386d5bc9188c0c498be
            preserve_default=False,
        ),
    ]
