# Generated by Django 2.0.8 on 2018-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuentaCorriente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descuentoProducto',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descuentoServicio',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dniCuit',
            field=models.CharField(error_messages={'blank': 'El dni/cuit es obligatorio', 'max_length': 'El dni/cuit puede tener a lo sumo 14 caracteres', 'unique': 'El dni/cuit ingresado ya existe'}, help_text='Dni/Cuit del Cliente', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDeCliente',
            field=models.CharField(choices=[('C', 'Comun'), ('E', 'Especial')], default='C', error_messages={'blank': 'El tipo de cliente es obligatorio'}, max_length=1),
        ),
    ]
