# Generated by Django 2.1.1 on 2018-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellidos',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CuentaCorriente',
            new_name='cuentaCorriente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='DescuentoProducto',
            new_name='descuentoProducto',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='DescuentoServicio',
            new_name='descuentoServicio',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Localidad',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombres',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='TipoDeCliente',
            new_name='tipoDeCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=30),
            preserve_default=False,
        ),
    ]
