
# Generated by Django 2.0.8 on 2018-09-28 20:26

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default=15678907, max_length=10),
            preserve_default=False,
        ),
    ]
