# Generated by Django 2.0.8 on 2018-10-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeClientes', '0003_auto_20181005_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
