# Generated by Django 2.1.1 on 2018-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Consulta'), ('Q', 'Quirurgica')], default='Tipo de Práctica aqui', max_length=25)),
                ('nombre', models.CharField(help_text='Ingresa el nombre del Servicio', max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tiempoEstimado', models.TimeField(help_text='Tiempo de Duración del Servicio')),
                ('precioManoDeObra', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
