# Generated by Django 2.0.9 on 2018-11-11 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeProductos', '0001_initial'),
        ('GestionDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(error_messages={'blank': 'La cantidad es obligatoria'})),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(error_messages={'blank': 'El tipo es obligatorio', 'max_length': 'El tipo de factura puede tener a lo sumo 1 caracteres'}, help_text='Tipo de factura', max_length=1, validators=[django.core.validators.RegexValidator(regex='^[A-B-C]{1}$')])),
                ('fecha', models.DateField(error_messages={'blank': 'La fecha es obligatoria'}, help_text='Fecha de la Factura')),
                ('total', models.IntegerField(default=0.0, error_messages={'blank': 'El importe es obligatorio'}, help_text='Importe total de la Factura')),
                ('baja', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(error_messages={'blank': 'El cliente es obligatorio'}, on_delete=django.db.models.deletion.CASCADE, to='GestionDeClientes.Cliente')),
                ('detalles', models.ManyToManyField(through='GestionDeFacturas.DetalleFactura', to='GestionDeProductos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(error_messages={'blank': 'La Factura es obligatoria'}, help_text='Ingrese numero de Factura', on_delete=django.db.models.deletion.CASCADE, to='GestionDeFacturas.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(error_messages={'blank': 'Debe ingresar al menos un producto'}, on_delete=django.db.models.deletion.CASCADE, to='GestionDeProductos.Producto'),
        ),
    ]
