# Generated by Django 2.1.dev20180423170307 on 2019-12-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeProductos', '0001_initial'),
        ('GestionDePracticas', '0001_initial'),
        ('GestionDeFacturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDePracticas.Practica'),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(through='GestionDeFacturas.DetalleFactura', to='GestionDeProductos.Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(error_messages={'blank': 'La Factura es obligatoria'}, help_text='Ingrese numero de Factura', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='GestionDeFacturas.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(error_messages={'blank': 'Debe ingresar al menos un producto'}, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='GestionDeProductos.Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('id', 'practica')},
        ),
        migrations.AlterUniqueTogether(
            name='detallefactura',
            unique_together={('factura', 'producto')},
        ),
        migrations.AlterIndexTogether(
            name='detallefactura',
            index_together={('factura', 'producto')},
        ),
    ]
