# Generated by Django 2.0.8 on 2018-11-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeFacturas', '0001_initial'),
        ('GestionDeProductos', '0001_initial'),
        ('GestionDePracticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'El producto es obligatorio'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDePracticas.Practica'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(error_messages={'blank': 'La Factura es obligatoria'}, help_text='Ingrese numero de Factura', on_delete=django.db.models.deletion.CASCADE, to='GestionDeFacturas.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(error_messages={'blank': 'Debe ingresar al menos un producto'}, on_delete=django.db.models.deletion.CASCADE, to='GestionDeProductos.Producto'),
        ),
    ]
