# Generated by Django 2.0.8 on 2018-11-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeFacturas', '0002_auto_20181121_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pago',
        ),
    ]
